apiVersion: v1
kind: Service
metadata:
  name: {{ include "bolt-prediction.fullname" . }}-api
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "bolt-prediction.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  annotations:
    {{- toYaml .Values.api.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bolt-prediction.componentSelectorLabels" (dict "component" "api" "Values" .Values "Release" .Release "Chart" .Chart) | nindent 4 }}
