{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bolt-prediction.fullname" . }}-secret
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "bolt-prediction.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
stringData:
  {{- range $key, $value := .Values.secret.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
